---
name: Check Pull Request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  checks: write
  pull-requests: write
  actions: read
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-actionlint@v1

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: build/test-results/test
