---
name: Check Pull Request

on:
  pull_request:
    branches:
      - main


jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-actionlint@v1

  pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: PR Title conforms to Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - run: ./gradlew build

      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: build/test-results/test
