name: Maintenance tasks

on:
  workflow_dispatch:
  schedule:
    - cron: "22 2 * * *"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Gradle Wrapper
        uses: paulschuberth/update-gradle-wrapper-action@customize-commit-messages
        with:
          repo-token: ${{ secrets.PAT }}
          commit-message-template: 'chore(deps): Bump Gradle Wrapper to %targetVersion%'
