---
name: Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          token: ${{ secrets.PAT }}
          config-file: release-please-config.json
          release-type: simple
          extra-files: |
            build.gradle.kts
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":false},
              {"type":"perf", "section": "Performance Improvements"}
            ]
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}

  publish:
    runs-on: ubuntu-latest
    needs: [ release-please ]
    if: ${{ needs.release-please.outputs.releases_created }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3

        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          USERNAME: ${{ env.GITHUB_ACTOR }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    runs-on: ubuntu-latest
    needs: [ publish ]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Build Docs
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dokkaHtml

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build/dokka/html

      - name: Publish Docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
