---
name: 'Test Report'
on:
  workflow_run:
    workflows: ['Check Pull Request']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: JUnit Tests
        path: '*.xml'
        reporter: java-junit
